### ISSUE TITLE
Drop to and run via mods folder.

### ISSUE THREAD

**Issue by CountBleck** [0x150/femboy-flooder#3]
Based off of #2, make it copy itself to the mods folder so it is run whenever a modded version of Minecraft starts.
This should only occur if the flooder is ran as a standalone program.

If the platform is Windows, give the copy the hidden **and** system attributes (to make sure almost no one finds it).
I'm not sure what to do if the platform is Unix-based, other than to prefix the name of the copy with a dot.

Ideally it should be able to run via Forge and Fabric.

**Comment by 0x150** [comment]
thats going into felony territory

**Comment by Semisol** [comment]
> thats going into felony territory

"utility mod to corrupt a server's bios"
